from .prefixes import prefixes
from .spells import spells
from .suffixes import suffixes
from .codify import codify
from .find_suffix import find_suffix
from .get_alphabet import get_alphabet
from .proper_case import proper_case
from .send import send
from .split import split
from .religions import religions
from .drops import drops
from .skills import skills
