spells = {
    "fireball": {
        "type": "Elemental Magics",
        "skill_begin": 0,
        "fizzle_stop": 20,
    },
    "icebolt": {
        "type": "Elemental Magics",
        "skill_begin": 20,
        "fizzle_stop": 45,
    },
    "flaming arrow": {
        "type": "Elemental Magics",
        "skill_begin": 40,
        "fizzle_stop": 60,
    },
    "blizzard": {
        "type": "Elemental Magics",
        "skill_begin": 55,
        "fizzle_stop": 75,
    },
    "flame strike": {
        "type": "Elemental Magics",
        "skill_begin": 70,
        "fizzle_stop": 90,
    },
    "wraith": {
        "type": "Elemental Magics",
        "skill_begin": 80,
        "fizzle_stop": 95,
    },
    "banshees wail": {
        "type": "Elemental Magics",
        "skill_begin": 90,
        "fizzle_stop": 105,
    },
    "firewall": {
        "type": "Elemental Magics",
        "skill_begin": 100,
        "fizzle_stop": 115,
    },
    "ice nova": {
        "type": "Elemental Magics",
        "skill_begin": 115,
        "fizzle_stop": 135,
    },
    "earthquake": {
        "type": "Elemental Magics",
        "skill_begin": 130,
        "fizzle_stop": 150,
    },
    "charged bolt": {
        "type": "Elemental Magics",
        "skill_begin": 145,
        "fizzle_stop": 165,
    },
    "meteor storm": {
        "type": "Elemental Magics",
        "skill_begin": 160,
        "fizzle_stop": 180,
    },
    "decrepify": {
        "type": "Elemental Magics",
        "skill_begin": 175,
        "fizzle_stop": 205,
    },
    "chaos bolt": {
        "type": "Elemental Magics",
        "skill_begin": 200,
        "fizzle_stop": 210,
    },
    "poison cloud": {"type": "Necromancy", "skill_begin": 1, "fizzle_stop": 25},
    "dark touch": {"type": "Necromancy", "skill_begin": 20, "fizzle_stop": 45},
    "burning rain": {
        "type": "Necromancy",
        "skill_begin": 45,
        "fizzle_stop": 65,
    },
    "summon slimes": {
        "type": "Necromancy",
        "skill_begin": 65,
        "fizzle_stop": 90,
    },
    "cowardice": {"type": "Necromancy", "skill_begin": 75, "fizzle_stop": 90},
    "death darts": {
        "type": "Necromancy",
        "skill_begin": 90,
        "fizzle_stop": 105,
    },
    "curse": {"type": "Necromancy", "skill_begin": 100, "fizzle_stop": 115},
    "weaken": {"type": "Necromancy", "skill_begin": 120, "fizzle_stop": 135},
    "raise dead": {
        "type": "Necromancy",
        "skill_begin": 130,
        "fizzle_stop": 150,
    },
    "slowed actions": {
        "type": "Necromancy",
        "skill_begin": 145,
        "fizzle_stop": 165,
    },
    "summon spiders": {
        "type": "Necromancy",
        "skill_begin": 160,
        "fizzle_stop": 180,
    },
    "apocalypse": {
        "type": "Necromancy",
        "skill_begin": 175,
        "fizzle_stop": 210,
    },
    "holy aura": {"type": "Thaumaturgy", "skill_begin": 0, "fizzle_stop": 15},
    "lesser heal": {
        "type": "Thaumaturgy",
        "skill_begin": 15,
        "fizzle_stop": 30,
    },
    "shield": {"type": "Thaumaturgy", "skill_begin": 30, "fizzle_stop": 45},
    "hermes speed": {
        "type": "Thaumaturgy",
        "skill_begin": 25,
        "fizzle_stop": 45,
    },
    "cure poison": {
        "type": "Thaumaturgy",
        "skill_begin": 40,
        "fizzle_stop": 55,
    },
    "healing wind": {
        "type": "Thaumaturgy",
        "skill_begin": 25,
        "fizzle_stop": 55,
    },
    "nature shield": {
        "type": "Thaumaturgy",
        "skill_begin": 25,
        "fizzle_stop": 55,
    },
    "empower": {"type": "Thaumaturgy", "skill_begin": 50, "fizzle_stop": 65},
    "antimagic": {"type": "Thaumaturgy", "skill_begin": 60, "fizzle_stop": 75},
    "holy armour": {
        "type": "Thaumaturgy",
        "skill_begin": 70,
        "fizzle_stop": 85,
    },
    "holy strike": {
        "type": "Thaumaturgy",
        "skill_begin": 100,
        "fizzle_stop": 115,
    },
    "true seeing": {
        "type": "Thaumaturgy",
        "skill_begin": 110,
        "fizzle_stop": 125,
    },
    "bless": {"type": "Thaumaturgy", "skill_begin": 75, "fizzle_stop": 125},
    "greater heal": {
        "type": "Thaumaturgy",
        "skill_begin": 120,
        "fizzle_stop": 135,
    },
    "holy lightning": {
        "type": "Thaumaturgy",
        "skill_begin": 130,
        "fizzle_stop": 160,
    },
    "exorcism": {"type": "Thaumaturgy", "skill_begin": 140, "fizzle_stop": 185},
    "banish": {"type": "Thaumaturgy", "skill_begin": 175, "fizzle_stop": 205},
    "magic missile": {"type": "Wizardry", "skill_begin": 1, "fizzle_stop": 20},
    "night sight": {"type": "Wizardry", "skill_begin": 10, "fizzle_stop": 30},
    "lightning": {"type": "Wizardry", "skill_begin": 10, "fizzle_stop": 30},
    "illusionary menace": {
        "type": "Wizardry",
        "skill_begin": 30,
        "fizzle_stop": 45,
    },
    "chain lightning": {
        "type": "Wizardry",
        "skill_begin": 40,
        "fizzle_stop": 60,
    },
    "town portal": {"type": "Wizardry", "skill_begin": 50, "fizzle_stop": 70},
    "nova": {"type": "Wizardry", "skill_begin": 65, "fizzle_stop": 85},
    "flash": {"type": "Wizardry", "skill_begin": 75, "fizzle_stop": 90},
    "summon wolf": {"type": "Wizardry", "skill_begin": 85, "fizzle_stop": 105},
    "polymorph": {"type": "Wizardry", "skill_begin": 95, "fizzle_stop": 115},
    "energy bolt": {"type": "Wizardry", "skill_begin": 115, "fizzle_stop": 135},
    "medusas stare": {
        "type": "Wizardry",
        "skill_begin": 130,
        "fizzle_stop": 145,
    },
    "mind blast": {"type": "Wizardry", "skill_begin": 135, "fizzle_stop": 155},
    "teleport": {"type": "Wizardry", "skill_begin": 150, "fizzle_stop": 170},
    "ethereal gate": {
        "type": "Wizardry",
        "skill_begin": 160,
        "fizzle_stop": 180,
    },
    "nauseate": {"type": "Wizardry", "skill_begin": 175, "fizzle_stop": 205},
}

